//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.LangResources {
    using System;
    
    ///   Strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class english
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Prevents a default instance of the <see cref="english"/> class from being created.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal english()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                // Lazy initialization of the ResourceManager
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.LangResources.english", typeof(english).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add
        {
            get
            {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string CompleteBackup
        {
            get
            {
                return ResourceManager.GetString("CompleteBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string delete
        {
            get
            {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Differential.
        /// </summary>
        public static string DifferentialBackup
        {
            get
            {
                return ResourceManager.GetString("DifferentialBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string edit
        {
            get
            {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to execute.
        /// </summary>
        public static string execute
        {
            get
            {
                return ResourceManager.GetString("execute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Job Name.
        /// </summary>
        public static string JobName
        {
            get
            {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Jobs Management.
        /// </summary>
        public static string JobsTitle
        {
            get
            {
                return ResourceManager.GetString("JobsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Source Path.
        /// </summary>
        public static string SourcePath
        {
            get
            {
                return ResourceManager.GetString("SourcePath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Target Path.
        /// </summary>
        public static string TargetPath
        {
            get
            {
                return ResourceManager.GetString("TargetPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Validate
        {
            get
            {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
    }
}
